### ISSUE TITLE
Sidemenu and Status Bar interaction

### ISSUE THREAD

**Issue by charlesvinette** [wonderkiln/WKAwesomeMenu#5]
Hey Adrian,

For now there is a problem with the interaction between side menu and "subview" being shown. If we change the view, the status bar disappears until we bring the subview in full screen and then re-appears making the whole transition "choppy".

**Comment by hrishikeshnewage** [comment]
Hi,

I am having the same problem, while going to a screen from side menu.
The new screen changes the layouts such that, the status bar overlaps over the new screen.
Please provide a fix for the same.
