### ISSUE TITLE
Fatal Exception on cells dequeue

### ISSUE THREAD

**Issue by GZaccaroni** [wonderkiln/WKAwesomeMenu#6]
Sometime i receive that error:

> Fatal Exception: NSInternalInconsistencyException
> unable to dequeue a cell with identifier MenuTableViewCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard

Can you help me? Thanks in advance

**Comment by austinkettner** [comment]
Looking into it @GZaccaroni

**Comment by adrianmteo** [comment]
Hi @GZaccaroni, did you register the class in `viewDidLoad`?

```
self.tableView.registerClass(MenuTableViewCell.self,
            forCellReuseIdentifier: "MenuTableViewCell")
```

**Comment by GZaccaroni** [comment]
I have used the code of the example!! So yes! It happens only on iOS 8

**Comment by austinkettner** [comment]
As per the move to Swift 3 and iOS 10 support, this is no longer an issue as we are not directly supporting iOS 8.
