### ISSUE TITLE
Circle indication issue

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [wonderkiln/WKAwesomeMenu#8]
Thank you for this wonderful pod 👍 

I found an issue with the indicator circle on Side menu.
Say I have an option to send an email in my nth controller. Whenever it opens the mail controller and navigates back to the app, the circle indicator moves to first option by default where as it should indicate the nth option. Any solution available for this issue?

**Comment by austinkettner** [comment]
Looking into it! Will close this ticket once resolved. Expect an updated response soon @AnnieNinaJoyceV

**Comment by AnnieNinaJoyceV** [comment]
Thank you @austinkettner :)

**Comment by adrianmteo** [comment]
Hi @AnnieNinaJoyceV, I am thinking to save a local variable with the index of the current selected nth controller in the `MenuTableViewController` and in `viewDidAppear` just select the nth cell from the table view. Hope this helps :)

**Comment by AnnieNinaJoyceV** [comment]
@adrianitech Hey! Sorry for very delayed reply.
Yes keeping a local variable will work (made it work that way as well), but I was wondering why it wasn't included in the original class itself. :)
